name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  push:
  pull_request:
  issue_comment:
    types: [created]


jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello

      # This step prints an output (time) from the previous step's action.
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'

      #
      - name: fail
        id: main
        run: |
          cd xxx
          if [ $? -eq 0 ]
          then
            echo "yep"
            echo ::set-output name=state::"sucess"
          else
            echo "nope"
            echo ::set-output name=state::"failure"
          fi
        continue-on-error: true

      - name: fail
        if: steps.main.outputs.state == "failure"
        run: |
          cd xxx
          if [ $? -eq 0 ]
          then
            echo "yep2"
          else
            echo "nope3"
          fi
