name: Secrets

on:
  push:
    branches: [ master ]

jobs:
  build:

    name: Secret
    runs-on: ubuntu-latest

    steps:
      - name: Can i See this secret?
        run: echo 'Secret - ${{ secrets.TESTSECRET }}.'
